---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon EKS Service Role'

Parameters:
  ClusterName:
    Type: String
    Description: EKS Cluster Name

  SecurityGroup:
    Description: Security Group Id
    Type: "List<AWS::EC2::SecurityGroup::Id>"

  SubnetIDs:
    Description: Subnet IDs
    Type: "List<AWS::EC2::Subnet::Id>"

Resources:
  AWSEksCluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: !Ref ClusterName
      Version: "1.10"
      RoleArn: !ImportValue eks-vc-role
      ResourcesVpcConfig:
        SecurityGroupIds: [!Ref SecurityGroup]
        SubnetIds: [!Ref SubnetIDs]
