---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon EKS Service Role'

Parameters:
  EKSName:
    Type: String
    Description: EKS Cluster Name

  Environment:
    Type: String
    Default: "dev"
    AllowedValues: ["dev", "stage", "prod"]

Resources:
  AWSEksCluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: !Ref EKSName
      Version: "1.10"
      RoleArn: !ImportValue eks-vc-role
      ResourcesVpcConfig:
        SecurityGroupIds: 
          - "sg-01e735987600fb036"
        SubnetIds: 
          - "subnet-02e44c62dae6d8ee4"
          - "subnet-0549eea9a63e1f4fc"
          - "subnet-0ca67dc7332016ce0"
