---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon EKS Service Role'

Parameters:
  EKSName:
    Type: String
    Description: EKS Cluster Name

  SecurityGroupIDs:
    Description: Security Group Id
    Type: "List<AWS::EC2::SecurityGroup::Id>"

  SubnetIDs:
    Description: Subnet IDs
    Type: "List<AWS::EC2::Subnet::Id>"

  Environment:
    Type: String
    Default: "dev"
    AllowedValues: ["dev", "stage", "prod"]

Resources:
  AWSEksCluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: !Ref EKSName
      Version: "1.10"
      RoleArn: !ImportValue eks-vc-role
      ResourcesVpcConfig:
        SecurityGroupIds: !Ref SecurityGroupIDs
        SubnetIds: !Ref SubnetIDs
