---
- hosts: localhost
  connection: local
  tasks:
  - name: eks-cluster
    cloudformation:
      stack_name: "eks-bc-cluster"
      state: "present"
      region: "us-west-2"
      disable_rollback: false
      template: "aws-codepipeline.yml"
      template_parameters:
        CodepipelineBucket: "codepipeline-12332310909"
        Repository: "terraform-templates"
        OAuthToken: "68611b4eafed340eb1aee74189c9cb7a191fe365"
        Owner: "vinicavalcanti"
      tags:
        Stack: "ansible-cloudformation"